export const languages = [
  {
    name:"HTML",
    backgroundColor:"#E2680F",
    color:"#f9f4da",
  },
  {
    name:"CSS",
    backgroundColor:"#328af1",
    color:"#f9f4da",
  },
  {
    name:"JavaScript",
    backgroundColor:"#f4eb13",
    color:"#1e1e1e",
  },
  {
    name:"React",
    backgroundColor:"#2ed3e9",
    color:"#1e1e1e",
  },
  {
    name:"TypeScript",
    backgroundColor:"#298ec6",
    color:"#f9f4da",
  },
  {
    name:"Node.js",
    backgroundColor:"#599137",
    color:"#f9f4da",
  },
  {
    name:"Python",
    backgroundColor:"#f4eb13",
    color:"#1e1e1e",
  },
   {
    name:"Ruby",
    backgroundColor:"#d61919ff",
    color:"#f9f4da",
  },
   {
    name:"Assembly",
    backgroundColor:"#08365cff",
    color:"#f9f4da",
  }
];